spring:
    mvc:
        view:
            prefix: /WEB-INF/views/jsp/
            suffix: .jsp
    datasource:
        hikari:
            connection-timeout: 20000
            maximum-pool-size: 5
        url: jdbc:postgresql://db:5432/spring_mvc # you can override this when running on the command line by using the argument --spring.datasource.url=<your jdbc connection>
        driver-class-name: org.postgresql.Driver
        username: postgres
        password:
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL95Dialect
        hibernate:
            ddl-auto: create